name: release

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: setup CPython
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          cache-dependency-path: "requirements-dev.lock"
          python-version-file: ".python-version"

      - name: install dependencies
        id: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.lock

      - name: lint
        if: ${{ always() && steps.install.outcome == 'success' }}
        run: |
          ruff check --output-format github .

      - name: format
        if: ${{ always() && steps.install.outcome == 'success' }}
        run: |
          ruff format --check .

  release:
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: setup CPython
        uses: actions/setup-python@v5
        with:
          cache: "pip"
          cache-dependency-path: "requirements.lock"
          python-version-file: ".python-version"

      - name: install dependencies
        id: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock

      # ここから自動リリース用の処理を記述
